package com.example.meet;

import jakarta.annotation.PostConstruct;
import org.springframework.http.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.web.server.ResponseStatusException;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;
import java.nio.file.*;
import java.security.*;
import java.time.*;
import java.util.*;

/** Persistent collaboration API; local accounts use salted PBKDF2 passwords and opaque server-side sessions. */
@RestController @RequestMapping("/api/v1")
public class CollaborationController {
 private final JdbcTemplate db; private final SecureRandom random=new SecureRandom(); private final Path files;
 CollaborationController(JdbcTemplate db,@Value("${signalroom.files:/data/uploads}") String root){this.db=db;this.files=Path.of(root).toAbsolutePath();}
 @PostConstruct void init(){
  db.execute("CREATE TABLE IF NOT EXISTS sr_users(id VARCHAR(36) PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(254) UNIQUE NOT NULL,password_hash VARCHAR(500) NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
  db.execute("CREATE TABLE IF NOT EXISTS sr_sessions(token_hash VARCHAR(64) PRIMARY KEY,user_id VARCHAR(36) NOT NULL,expires TIMESTAMP NOT NULL)");
  db.execute("CREATE TABLE IF NOT EXISTS sr_teams(id VARCHAR(36) PRIMARY KEY,name VARCHAR(120) NOT NULL,description VARCHAR(500),owner_id VARCHAR(36) NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
  db.execute("CREATE TABLE IF NOT EXISTS sr_members(team_id VARCHAR(36) NOT NULL,user_id VARCHAR(36) NOT NULL,role VARCHAR(15) NOT NULL,PRIMARY KEY(team_id,user_id))");
  db.execute("CREATE TABLE IF NOT EXISTS sr_channels(id VARCHAR(36) PRIMARY KEY,team_id VARCHAR(36) NOT NULL,name VARCHAR(100) NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
  db.execute("CREATE TABLE IF NOT EXISTS sr_messages(id VARCHAR(36) PRIMARY KEY,channel_id VARCHAR(36) NOT NULL,user_id VARCHAR(36) NOT NULL,body VARCHAR(4000) NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
  db.execute("CREATE TABLE IF NOT EXISTS sr_events(id VARCHAR(36) PRIMARY KEY,organizer_id VARCHAR(36) NOT NULL,title VARCHAR(200) NOT NULL,starts TIMESTAMP NOT NULL,ends TIMESTAMP NOT NULL,room VARCHAR(64),created TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
  db.execute("CREATE TABLE IF NOT EXISTS sr_files(id VARCHAR(36) PRIMARY KEY,team_id VARCHAR(36) NOT NULL,owner_id VARCHAR(36) NOT NULL,display_name VARCHAR(255) NOT NULL,mime VARCHAR(120),size_bytes BIGINT NOT NULL,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
  try{Files.createDirectories(files);}catch(Exception e){throw new IllegalStateException(e);}
 }
 record AuthInput(String name,String email,String password){}
 record TeamInput(String name,String description){}
 record ChannelInput(String name){}
 record MessageInput(String body){}
 record EventInput(String title,String starts,String ends,String room){}
 record InviteInput(String email){}
 private Object col(Map<String,Object> row,String name){return row.getOrDefault(name,row.get(name.toUpperCase(Locale.ROOT)));}
 private String id(){return UUID.randomUUID().toString();}
 private String token(){byte[] bytes=new byte[32];random.nextBytes(bytes);return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);}
 private String sha(String s){try{byte[] b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(java.nio.charset.StandardCharsets.UTF_8));return HexFormat.of().formatHex(b);}catch(Exception ex){throw new IllegalStateException(ex);}}
 private String password(String raw,String salt){try{byte[] b=SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(new PBEKeySpec(raw.toCharArray(),HexFormat.of().parseHex(salt),210000,256)).getEncoded();return HexFormat.of().formatHex(b);}catch(Exception ex){throw new IllegalStateException(ex);}}
 private Map<String,Object> session(String uid){String bearer=token();db.update("INSERT INTO sr_sessions(token_hash,user_id,expires) VALUES(?,?,?)",sha(bearer),uid,java.sql.Timestamp.from(Instant.now().plus(Duration.ofDays(7))));return Map.of("token",bearer,"user",db.queryForMap("SELECT id,name,email FROM sr_users WHERE id=?",uid));}
 private String current(String authorization){if(authorization==null||!authorization.startsWith("Bearer "))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Sign in required");String hashed=sha(authorization.substring(7));List<String> ids=db.query("SELECT user_id FROM sr_sessions WHERE token_hash=? AND expires>CURRENT_TIMESTAMP",(r,n)->r.getString(1),hashed);if(ids.isEmpty())throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Session expired");return ids.get(0);}
 private void required(boolean condition,HttpStatus status,String msg){if(!condition)throw new ResponseStatusException(status,msg);}
 private String member(String team,String user){List<String> roles=db.query("SELECT role FROM sr_members WHERE team_id=? AND user_id=?",(r,n)->r.getString(1),team,user);required(!roles.isEmpty(),HttpStatus.FORBIDDEN,"Team membership required");return roles.get(0);}
 private String teamForChannel(String channel,String uid){List<String> teams=db.query("SELECT team_id FROM sr_channels WHERE id=?",(r,n)->r.getString(1),channel);required(!teams.isEmpty(),HttpStatus.NOT_FOUND,"Channel not found");member(teams.get(0),uid);return teams.get(0);}
 @PostMapping("/auth/register") public Map<String,Object> register(@RequestBody AuthInput a){required(a.name()!=null&&!a.name().isBlank()&&a.email()!=null&&a.email().contains("@")&&a.password()!=null&&a.password().length()>=10,HttpStatus.BAD_REQUEST,"Name, email and password (10+ characters) required");String salt=HexFormat.of().formatHex(SecureRandom.getSeed(16)),uid=id();try{db.update("INSERT INTO sr_users(id,name,email,password_hash) VALUES(?,?,?,?)",uid,a.name().trim(),a.email().trim().toLowerCase(Locale.ROOT),salt+":"+password(a.password(),salt));}catch(org.springframework.dao.DataIntegrityViolationException e){throw new ResponseStatusException(HttpStatus.CONFLICT,"Email already registered");}return session(uid);}
 @PostMapping("/auth/login") public Map<String,Object> login(@RequestBody AuthInput a){required(a.email()!=null&&a.password()!=null,HttpStatus.BAD_REQUEST,"Credentials required");List<Map<String,Object>> rs=db.queryForList("SELECT id,password_hash FROM sr_users WHERE email=?",a.email().trim().toLowerCase(Locale.ROOT));required(!rs.isEmpty(),HttpStatus.UNAUTHORIZED,"Invalid credentials");String[] hash=((String)col(rs.get(0),"password_hash")).split(":");required(MessageDigest.isEqual(password(a.password(),hash[0]).getBytes(),hash[1].getBytes()),HttpStatus.UNAUTHORIZED,"Invalid credentials");return session((String)col(rs.get(0),"id"));}
 @GetMapping("/auth/me") public Map<String,Object> me(@RequestHeader(value="Authorization",required=false) String auth){return db.queryForMap("SELECT id,name,email FROM sr_users WHERE id=?",current(auth));}
 @PostMapping("/auth/logout") public Map<String,String> logout(@RequestHeader(value="Authorization", required=false) String auth){current(auth);db.update("DELETE FROM sr_sessions WHERE token_hash=?",sha(auth.substring(7)));return Map.of("status","signed_out");}
 @GetMapping("/teams") public List<Map<String,Object>> teams(@RequestHeader(value="Authorization", required=false) String auth){return db.queryForList("SELECT t.id,t.name,t.description,m.role FROM sr_teams t JOIN sr_members m ON t.id=m.team_id WHERE m.user_id=? ORDER BY t.created DESC",current(auth));}
 @PostMapping("/teams") public Map<String,Object> createTeam(@RequestHeader(value="Authorization", required=false) String auth,@RequestBody TeamInput a){String user=current(auth);required(a.name()!=null&&!a.name().isBlank()&&a.name().length()<=120,HttpStatus.BAD_REQUEST,"Team name required");String id=id(),channel=id();db.update("INSERT INTO sr_teams(id,name,description,owner_id) VALUES(?,?,?,?)",id,a.name().trim(),a.description(),user);db.update("INSERT INTO sr_members(team_id,user_id,role) VALUES(?,?,?)",id,user,"OWNER");db.update("INSERT INTO sr_channels(id,team_id,name) VALUES(?,?,?)",channel,id,"General");return Map.of("id",id,"channelId",channel);}
 @GetMapping("/teams/{team}/members") public List<Map<String,Object>> members(@RequestHeader(value="Authorization", required=false) String auth,@PathVariable String team){member(team,current(auth));return db.queryForList("SELECT u.id,u.name,u.email,m.role FROM sr_members m JOIN sr_users u ON u.id=m.user_id WHERE m.team_id=?",team);}
 @PostMapping("/teams/{team}/members") public Map<String,String> addMember(@RequestHeader(value="Authorization", required=false) String auth,@PathVariable String team,@RequestBody InviteInput input){String role=member(team,current(auth));required(role.equals("OWNER")||role.equals("ADMIN"),HttpStatus.FORBIDDEN,"Only team admins can invite");List<String> ids=db.query("SELECT id FROM sr_users WHERE email=?",(r,n)->r.getString(1),input.email()==null?"":input.email().trim().toLowerCase(Locale.ROOT));required(!ids.isEmpty(),HttpStatus.NOT_FOUND,"User must register first");db.update("INSERT INTO sr_members(team_id,user_id,role) SELECT ?,?,? WHERE NOT EXISTS (SELECT 1 FROM sr_members WHERE team_id=? AND user_id=?)",team,ids.get(0),"MEMBER",team,ids.get(0));return Map.of("status","added");}
 @GetMapping("/teams/{team}/channels") public List<Map<String,Object>> channels(@RequestHeader(value="Authorization", required=false) String auth,@PathVariable String team){member(team,current(auth));return db.queryForList("SELECT id,team_id,name FROM sr_channels WHERE team_id=? ORDER BY created",team);}
 @PostMapping("/teams/{team}/channels") public Map<String,String> addChannel(@RequestHeader(value="Authorization", required=false) String auth,@PathVariable String team,@RequestBody ChannelInput input){String role=member(team,current(auth));required(!role.equals("MEMBER"),HttpStatus.FORBIDDEN,"Admins only");required(input.name()!=null&&!input.name().isBlank(),HttpStatus.BAD_REQUEST,"Name required");String id=id();db.update("INSERT INTO sr_channels(id,team_id,name) VALUES(?,?,?)",id,team,input.name().trim());return Map.of("id",id);}
 @GetMapping("/channels/{channel}/messages") public List<Map<String,Object>> messages(@RequestHeader(value="Authorization", required=false) String auth,@PathVariable String channel){teamForChannel(channel,current(auth));return db.queryForList("SELECT m.id,m.body,m.created,u.name AS author,m.user_id FROM sr_messages m JOIN sr_users u ON u.id=m.user_id WHERE m.channel_id=? ORDER BY m.created ASC LIMIT 200",channel);}
 @PostMapping("/channels/{channel}/messages") public Map<String,String> message(@RequestHeader(value="Authorization", required=false) String auth,@PathVariable String channel,@RequestBody MessageInput input){String uid=current(auth);teamForChannel(channel,uid);required(input.body()!=null&&!input.body().isBlank()&&input.body().length()<=4000,HttpStatus.BAD_REQUEST,"Message must be 1–4000 characters");String mid=id();db.update("INSERT INTO sr_messages(id,channel_id,user_id,body) VALUES(?,?,?,?)",mid,channel,uid,input.body().trim());return Map.of("id",mid);}
 @GetMapping("/events") public List<Map<String,Object>> events(@RequestHeader(value="Authorization", required=false) String auth){return db.queryForList("SELECT id,title,starts,ends,room FROM sr_events WHERE organizer_id=? ORDER BY starts",current(auth));}
 @PostMapping("/events") public Map<String,String> event(@RequestHeader(value="Authorization", required=false) String auth,@RequestBody EventInput input){String uid=current(auth);try{LocalDateTime start=LocalDateTime.parse(input.starts()),end=LocalDateTime.parse(input.ends());required(end.isAfter(start)&&input.title()!=null&&!input.title().isBlank(),HttpStatus.BAD_REQUEST,"Invalid event");String id=id();db.update("INSERT INTO sr_events(id,organizer_id,title,starts,ends,room) VALUES(?,?,?,?,?,?)",id,uid,input.title(),java.sql.Timestamp.valueOf(start),java.sql.Timestamp.valueOf(end),input.room());return Map.of("id",id);}catch(java.time.format.DateTimeParseException e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Dates must use YYYY-MM-DDTHH:mm");}}
 @GetMapping("/teams/{team}/files") public List<Map<String,Object>> files(@RequestHeader(value="Authorization", required=false) String auth,@PathVariable String team){member(team,current(auth));return db.queryForList("SELECT f.id,f.display_name,f.mime,f.size_bytes,f.created,u.name AS uploaded_by FROM sr_files f JOIN sr_users u ON u.id=f.owner_id WHERE team_id=? ORDER BY created DESC",team);}
 @PostMapping(value="/teams/{team}/files",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public Map<String,String> upload(@RequestHeader(value="Authorization", required=false) String auth,@PathVariable String team,@RequestParam("file") MultipartFile file){String uid=current(auth);member(team,uid);required(!file.isEmpty()&&file.getSize()<=15_000_000,HttpStatus.BAD_REQUEST,"Files must be 1 byte to 15 MB");String id=id();try{Files.copy(file.getInputStream(),files.resolve(id),StandardCopyOption.REPLACE_EXISTING);}catch(Exception e){throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,"Could not store file");}String name=Optional.ofNullable(file.getOriginalFilename()).orElse("upload");name=Path.of(name).getFileName().toString();db.update("INSERT INTO sr_files(id,team_id,owner_id,display_name,mime,size_bytes) VALUES(?,?,?,?,?,?)",id,team,uid,name,file.getContentType(),file.getSize());return Map.of("id",id);}
 @GetMapping("/files/{id}") public ResponseEntity<byte[]> download(@RequestHeader(value="Authorization", required=false) String auth,@PathVariable String id){String uid=current(auth);List<Map<String,Object>> meta=db.queryForList("SELECT team_id,display_name,mime FROM sr_files WHERE id=?",id);required(!meta.isEmpty(),HttpStatus.NOT_FOUND,"File not found");member((String)col(meta.get(0),"team_id"),uid);try{byte[] data=Files.readAllBytes(files.resolve(id));return ResponseEntity.ok().contentType(MediaType.APPLICATION_OCTET_STREAM).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+((String)col(meta.get(0),"display_name")).replace("\"","")+"\"").body(data);}catch(Exception e){throw new ResponseStatusException(HttpStatus.NOT_FOUND,"File content missing");}}
}
