"use client";
import {use,useCallback,useEffect,useRef,useState} from 'react';
import {LiveKitRoom,VideoConference,RoomAudioRenderer,useParticipants} from '@livekit/components-react';
import {Diagnostics} from '../../../components/Diagnostics';import {Moderator} from '../../../components/Moderator';import {installProtocolTap} from '../../../lib/protocol-tap';import {useRouter} from 'next/navigation';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8080';type Credentials={token:string;serverUrl:string;room:string;role:string;identity:string};
function Occupancy(){const participants=useParticipants();return <span>{participants.length} connected / 60 maximum</span>}
export default function MeetingPage({params}:{params:Promise<{roomId:string}>}){const {roomId}=use(params);const router=useRouter();const [key,setKey]=useState(''),[role,setRole]=useState(''),[credentials,setCredentials]=useState<Credentials|null>(null),[status,setStatus]=useState('WAITING'),[error,setError]=useState(''),[showDiagnostics,setShowDiagnostics]=useState(false);const joiningRef=useRef(false);
useEffect(()=>{installProtocolTap();const k=sessionStorage.getItem(`signalroom:${roomId}:key`)||'';const r=sessionStorage.getItem(`signalroom:${roomId}:role`)||'';setKey(k);setRole(r);if(!k)setError('No admission ticket found. Return to the lobby and request access.');},[roomId]);
const join=useCallback(async()=>{if(!key||joiningRef.current)return;joiningRef.current=true;try{const res=await fetch(`${API}/api/join`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({room:roomId,accessKey:key})});if(!res.ok){const payload=await res.json();throw Error(payload.error||`Join rejected (${res.status})`)}setCredentials(await res.json());setError('');}catch(e){joiningRef.current=false;setError(String(e));}},[roomId,key]);
useEffect(()=>{if(!key||credentials)return;if(role==='HOST'){void join();return}let active=true;const poll=async()=>{try{const res=await fetch(`${API}/api/meetings/${roomId}/admissions/me`,{headers:{'X-Guest-Key':key}});if(!res.ok)throw Error('Admission ticket invalid');const json=await res.json();if(active){setStatus(json.STATUS||json.status);if((json.STATUS||json.status)==='APPROVED')void join();}}catch(e){if(active)setError(String(e))}};poll();const timer=setInterval(poll,2000);return()=>{active=false;clearInterval(timer)}},[key,role,join,roomId,credentials]);
const leave=async()=>{if(role!=='HOST'&&key)await fetch(`${API}/api/meetings/${roomId}/leave`,{method:'POST',headers:{'X-Guest-Key':key}}).catch(()=>{});router.push('/meet')};
return <div><header className="topbar"><span className="brand">◈ Signal<span>Room</span></span><div className="right"><span className="link">{roomId} · {role}</span><button className="secondary" onClick={()=>navigator.clipboard?.writeText(`${location.origin}/meet?room=${encodeURIComponent(roomId)}`)}>Copy invite URL</button><button className="secondary" onClick={()=>setShowDiagnostics(!showDiagnostics)}>{showDiagnostics?'Hide':'Show'} diagnostics</button><button className="secondary" onClick={leave}>Leave</button></div></header>{!credentials?<div className="panel" style={{margin:'8vh auto',maxWidth:540}}><h2>{role==='HOST'?'Starting meeting':'Waiting room'}</h2><p className="muted">{role==='HOST'?'Connecting as the host…':`Admission status: ${status}. Please wait for the host to approve your request.`}</p>{error&&<><p className="error">{error}</p><button className="secondary" onClick={()=>void join()}>Retry connection</button></>}</div>:<LiveKitRoom key={credentials.token} token={credentials.token} serverUrl={credentials.serverUrl} connect audio video options={{adaptiveStream:true,dynacast:true}} onDisconnected={leave}><div className="conference-shell"><div className="room-status"><Occupancy/><span>Encrypted SFU transport · {credentials.role}</span></div>{role==='HOST'&&<Moderator room={roomId} hostKey={key} onEnd={()=>router.push('/meet')}/>}<div className="conference" style={{gridTemplateColumns:showDiagnostics?'minmax(0,1fr) 360px':'1fr'}}><section className="meeting"><VideoConference/><RoomAudioRenderer/></section>{showDiagnostics&&<Diagnostics/>}</div></div></LiveKitRoom>}</div>}
