'use client';
import {useEffect,useState,FormEvent} from 'react';
import {useRouter} from 'next/navigation';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8080';
type Item=Record<string,any>;
const key=(o:Item,s:string)=>o[s]??o[s.toUpperCase()]??o[s.toLowerCase()];
export default function Dashboard(){
 const router=useRouter(); const [token,setToken]=useState(''),[me,setMe]=useState<Item|null>(null),[mode,setMode]=useState<'login'|'register'>('login');const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 const [tab,setTab]=useState('chat'),[teams,setTeams]=useState<Item[]>([]),[team,setTeam]=useState(''),[channels,setChannels]=useState<Item[]>([]),[channel,setChannel]=useState(''),[messages,setMessages]=useState<Item[]>([]),[body,setBody]=useState(''),[events,setEvents]=useState<Item[]>([]),[files,setFiles]=useState<Item[]>([]),[members,setMembers]=useState<Item[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(''),[query,setQuery]=useState('');
 const request=async(path:string,method='GET',payload?:unknown,override?:string):Promise<any>=>{const t=override??token;const r=await fetch(API+'/api/v1'+path,{method,headers:{...(t?{Authorization:'Bearer '+t}:{}),...(payload?{'Content-Type':'application/json'}:{})},body:payload?JSON.stringify(payload):undefined});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail||data.message||`Request failed ${r.status}`);return data};
 const loadTeams=async(t?:string)=>{const list=await request('/teams','GET',undefined,t);setTeams(list);if(!team&&list.length)setTeam(key(list[0],'id'))};
 useEffect(()=>{const t=localStorage.getItem('sr_token');if(t){setToken(t);request('/auth/me','GET',undefined,t).then(setMe).then(()=>loadTeams(t)).catch(()=>localStorage.removeItem('sr_token'));}},[]);
 useEffect(()=>{if(!team||!token)return;Promise.all([request(`/teams/${team}/channels`),request(`/teams/${team}/members`),request(`/teams/${team}/files`)]).then(([c,m,f])=>{setChannels(c);setMembers(m);setFiles(f);if(!c.some((x:Item)=>key(x,'id')===channel))setChannel(c[0]?key(c[0],'id'):'')}).catch(e=>setError(e.message));},[team,token]);
 const refreshMessages=async()=>{if(channel&&token)try{setMessages(await request(`/channels/${channel}/messages`))}catch(e:any){setError(e.message)}};
 useEffect(()=>{refreshMessages();if(!channel)return;const timer=setInterval(refreshMessages,2500);return()=>clearInterval(timer)},[channel,token]);
 useEffect(()=>{if(token)request('/events').then(setEvents).catch(()=>{})},[token]);
 const auth=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const res=await request('/auth/'+mode,'POST',{name,email,password},'');localStorage.setItem('sr_token',res.token);setToken(res.token);setMe(res.user);await loadTeams(res.token)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const createTeam=async()=>{const name=prompt('New team name');if(!name)return;try{const t=await request('/teams','POST',{name,description:''});await loadTeams();setTeam(t.id)}catch(e:any){setError(e.message)}};
 const createChannel=async()=>{if(!team)return;const name=prompt('New channel name');if(!name)return;try{await request(`/teams/${team}/channels`,'POST',{name});setChannels(await request(`/teams/${team}/channels`))}catch(e:any){setError(e.message)}};
 const invite=async()=>{const email=prompt('Registered member email');if(!email)return;try{await request(`/teams/${team}/members`,'POST',{email});setMembers(await request(`/teams/${team}/members`))}catch(e:any){setError(e.message)}};
 const send=async(e:FormEvent)=>{e.preventDefault();if(!body.trim())return;try{await request(`/channels/${channel}/messages`,'POST',{body});setBody('');await refreshMessages()}catch(e:any){setError(e.message)}};
 const upload=async(file:File)=>{const form=new FormData();form.append('file',file);const r=await fetch(`${API}/api/v1/teams/${team}/files`,{method:'POST',headers:{Authorization:'Bearer '+token},body:form});if(!r.ok){setError('File upload failed');return}setFiles(await request(`/teams/${team}/files`))};
 const download=async(f:Item)=>{const r=await fetch(`${API}/api/v1/files/${key(f,'id')}`,{headers:{Authorization:'Bearer '+token}});if(!r.ok){setError('Download failed');return}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=key(f,'display_name');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const event=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);try{await request('/events','POST',{title:data.get('title'),starts:data.get('starts'),ends:data.get('ends'),room:data.get('room')});setEvents(await request('/events'));setModal('')}catch(e:any){setError(e.message)}};
 const signout=()=>{request('/auth/logout','POST').catch(()=>{});localStorage.removeItem('sr_token');setToken('');setMe(null)};
 if(!me)return <main className="sr-auth"><div className="sr-auth-brand">◈ Signal<span>Room</span></div><section className="sr-auth-card"><div className="sr-kicker">YOUR WORKSPACE. YOUR CONVERSATIONS.</div><h1>Work together, from anywhere.</h1><p>Secure spaces for your teams, messages, files and video meetings.</p><form onSubmit={auth}>{mode==='register'&&<label>Full name<input required value={name} onChange={e=>setName(e.target.value)}/></label>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="sr-error">{error}</p>}<button className="sr-primary" disabled={busy}>{busy?'Working…':mode==='login'?'Sign in':'Create account'}</button></form><button className="sr-text-button" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'New to SignalRoom? Create an account':'Already registered? Sign in'}</button></section></main>;
 return <div className="sr-shell"><aside className="sr-rail"><div className="sr-logo">◈</div>{[['activity','⌂','Home'],['chat','▤','Chat'],['teams','▦','Teams'],['calendar','▣','Calendar'],['files','♧','Files'],['meetings','▣','Meet']].map(([id,glyph,label])=><button key={id} title={label} className={'sr-nav '+(tab===id?'active':'')} onClick={()=>setTab(id)}><b>{glyph}</b><small>{label}</small></button>)}<div className="sr-avatar" title={key(me,'name')}>{String(key(me,'name')).slice(0,1).toUpperCase()}</div></aside><aside className="sr-sidebar"><div className="sr-sidebar-top"><strong>SignalRoom</strong><button onClick={signout} title="Sign out">↪</button></div><h2>{({chat:'Chat',teams:'Teams',calendar:'Calendar',files:'Files',meetings:'Meetings',activity:'Activity'} as Item)[tab]}</h2><input className="sr-search" placeholder="Search your workspace" value={query} onChange={e=>setQuery(e.target.value)}/>{['chat','teams','files','activity'].includes(tab)&&<><div className="sr-sideheading">YOUR TEAMS <button onClick={createTeam}>＋</button></div>{teams.filter(t=>String(key(t,'name')).toLowerCase().includes(query.toLowerCase())).map(t=><button className={'sr-team '+(team===key(t,'id')?'active':'')} onClick={()=>setTeam(key(t,'id'))} key={key(t,'id')}><span className="sr-team-icon">{String(key(t,'name')).slice(0,1).toUpperCase()}</span>{key(t,'name')}</button>)}{team&&<><div className="sr-sideheading">CHANNELS <button onClick={createChannel}>＋</button></div>{channels.map(c=><button className={'sr-channel '+(channel===key(c,'id')?'active':'')} key={key(c,'id')} onClick={()=>{setChannel(key(c,'id'));setTab('chat')}}># {key(c,'name')}</button>)}</>}</>}{tab==='meetings'&&<p className="sr-muted">Instant video meetings, waiting rooms and host controls.</p>}</aside><main className="sr-content"><header className="sr-header"><div><span className="sr-breadcrumb">SignalRoom / {tab}</span><h1>{tab==='chat'?(channels.find(c=>key(c,'id')===channel)?.name||'Choose a channel'):({teams:'Manage teams',calendar:'Your calendar',files:'Shared files',meetings:'Video meetings',activity:'Overview'} as Item)[tab]}</h1></div><div className="sr-header-actions"><span className="sr-presence">● Available</span><span className="sr-user">{key(me,'name')}</span></div></header>{error&&<div className="sr-warning">{error}<button onClick={()=>setError('')}>×</button></div>}
 {tab==='chat'&&<div className="sr-chat"><div className="sr-chat-head"><span>#{channels.find(c=>key(c,'id')===channel)?.name||'No channel selected'}</span><span>{members.length} team members</span></div><div className="sr-messages">{messages.length===0?<div className="sr-empty">Start the conversation. Messages are saved and available to your team.</div>:messages.map(m=><article className="sr-message" key={key(m,'id')}><div className="sr-person">{String(key(m,'author')).slice(0,1).toUpperCase()}</div><div><div><strong>{key(m,'author')}</strong><time>{String(key(m,'created')).replace('T',' ').slice(0,16)}</time></div><p>{key(m,'body')}</p></div></article>)}</div><form onSubmit={send} className="sr-composer"><input placeholder={channel?'Message this channel…':'Select a channel'} disabled={!channel} value={body} onChange={e=>setBody(e.target.value)}/><button disabled={!channel} className="sr-primary">Send ➤</button></form></div>}
 {tab==='teams'&&<div className="sr-pad"><div className="sr-section-title"><h2>Team members</h2><button className="sr-primary" onClick={invite} disabled={!team}>+ Add member</button></div><div className="sr-table">{members.map(m=><div key={key(m,'id')} className="sr-table-row"><div className="sr-person">{String(key(m,'name')).slice(0,1)}</div><div><b>{key(m,'name')}</b><small>{key(m,'email')}</small></div><span className="sr-chip">{key(m,'role')}</span></div>)}</div><h2>Channels</h2><div className="sr-card-grid">{channels.map(c=><button className="sr-tile" key={key(c,'id')} onClick={()=>{setChannel(key(c,'id'));setTab('chat')}}><span>#</span><b>{key(c,'name')}</b><small>Open channel</small></button>)}</div></div>}
 {tab==='files'&&<div className="sr-pad"><div className="sr-section-title"><h2>Shared files</h2><label className="sr-primary sr-upload">+ Upload file<input type="file" hidden onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}} disabled={!team}/></label></div><p className="sr-muted">Files are visible to members of the selected team. Maximum upload size: 15 MB.</p><div className="sr-table">{files.map(f=><div className="sr-table-row" key={key(f,'id')}><span style={{fontSize:25}}>▧</span><div><b>{key(f,'display_name')}</b><small>{key(f,'uploaded_by')} · {Math.round(Number(key(f,'size_bytes'))/1024)} KB</small></div><button onClick={()=>download(f)}>Download ↓</button></div>)}</div></div>}
 {tab==='calendar'&&<div className="sr-pad"><div className="sr-section-title"><h2>Upcoming events</h2><button className="sr-primary" onClick={()=>setModal('event')}>+ New event</button></div><div className="sr-card-grid">{events.map(e=><div className="sr-tile" key={key(e,'id')}><span>▣</span><b>{key(e,'title')}</b><small>{String(key(e,'starts')).replace('T',' ').slice(0,16)}</small>{key(e,'room')&&<button onClick={()=>router.push('/room/'+key(e,'room'))}>Open meeting →</button>}</div>)}</div>{events.length===0&&<div className="sr-empty">No events scheduled yet.</div>}</div>}
 {tab==='meetings'&&<div className="sr-pad"><div className="sr-meeting-banner"><div><span className="sr-kicker">SIGNALROOM MEET</span><h2>Better meetings start here.</h2><p>Create or join an encrypted meeting with host approval, gallery view, screen sharing and up to 60 participants.</p><button className="sr-primary" onClick={()=>router.push('/meet')}>Start or join a meeting →</button></div><div className="sr-banner-icon">◈</div></div><div className="sr-card-grid"><div className="sr-tile"><b>Up to 60 attendees</b><small>LiveKit SFU with an admission limit</small></div><div className="sr-tile"><b>Meeting controls</b><small>Camera, microphone, screen sharing, waiting room</small></div></div></div>}
 {tab==='activity'&&<div className="sr-pad"><div className="sr-meeting-banner"><div><span className="sr-kicker">WELCOME BACK</span><h2>Hello, {String(key(me,'name')).split(' ')[0]}.</h2><p>Bring conversations, meetings and shared work together in one place.</p><button className="sr-primary" onClick={()=>setTab('meetings')}>Start a meeting →</button></div><div className="sr-banner-icon">◈</div></div><div className="sr-card-grid"><div className="sr-tile"><b>{teams.length} Teams</b><small>Workspaces you belong to</small></div><div className="sr-tile"><b>{events.length} Events</b><small>Scheduled meetings and plans</small></div><div className="sr-tile"><b>{files.length} Files</b><small>Shared in your selected team</small></div></div></div>}
 </main>{modal==='event'&&<div className="sr-overlay"><form onSubmit={event} className="sr-modal"><button type="button" className="sr-close" onClick={()=>setModal('')}>×</button><h2>Schedule an event</h2><label>Title<input name="title" required/></label><label>Starts<input name="starts" type="datetime-local" required/></label><label>Ends<input name="ends" type="datetime-local" required/></label><label>Meeting room ID (optional)<input name="room" placeholder="team-weekly-sync"/></label><button className="sr-primary">Create event</button></form></div>}</div>;
}
